services:
  bot:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: .
    container_name: telegram_vk_bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TG_TOKEN=${TG_TOKEN}
      - VK_TOKEN=${VK_TOKEN}
      - VK_GROUP=${VK_GROUP}
      - PUBLIC_IP=${PUBLIC_IP}
    volumes:
      - .:/app/storage
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/botctl/.ssh/botctl_key:/root/.ssh/id_ed25519:ro
