version: '3.8'

services:
  bot:
    build: .
    container_name: telegram_vk_bot
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TG_TOKEN=${TG_TOKEN}
      - VK_TOKEN=${VK_TOKEN}
      - VK_GROUP=${VK_GROUP}
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
